### ISSUE TITLE
ocular-gatsby: Overriding components fails during static build

### ISSUE THREAD

**Issue by jckr** [uber-web/ocular#125]
These are issues that arise when building a website (ie yarn build) vs running the development version.

```
0 | function getReactComponent(name, defaultComponent) {
  11 |   const component = registry[name] || defaultComponent;
> 12 |   assert(component !== undefined, name);
     |   ^
  13 |   return component;
  14 | }
  15 |


  WebpackError: AssertionError [ERR_ASSERTION]: EXAMPLES

  - component-registry.js:12 getReactComponent
    lib/Users/jerome/code/ocular/modules/gatsby/src/utils/component-registry.js:12:3

  - component-registry.js:18 getHeroExample
    lib/Users/jerome/code/ocular/modules/gatsby/src/utils/component-registry.js:18:20

  - hero.jsx:10 Hero.renderPage
    lib/Users/jerome/code/ocular/modules/gatsby/src/components/hero.jsx:10:5

  - hero.jsx:34 Object.children
    lib/Users/jerome/code/ocular/modules/gatsby/src/components/hero.jsx:34:26

```

in the getHeroExample function of component-registry we call 
```
const EXAMPLES = getReactComponent('EXAMPLES');
```
This may result in an error if EXAMPLES is not found in the registry. We can avoid this by adding a default argument like so: 
```
const EXAMPLES = getReactComponent('EXAMPLES', {});
```
but maybe we can have a safer default Hero component that doesn't try to load an example at all, and let that feature to be only overridable from the local tree.

Once this is fixed - 

```
 121 | // search
  122 |
> 123 | export const SearchContainer = styled.div(props => ({
      |                                                     ^
  124 |   position: 'relative',
  125 |   height: props.theme.sizing.scale1000,
  126 |   marginBottom: '20px',


  WebpackError: TypeError: Cannot read property 'scale1000' of undefined

  - index.js:123
    lib/Users/jerome/code/ocular/modules/gatsby/src/components/styled/index.js:123:53
```

In the styled components file, somehow the theme doesn't work. I don't know how / why this is different between the dev and prod version. 

One thing that I've tried is go all in and replace styled components with baseUI using https://baseweb.design/getting-started/installation/ recommendations for Gatsby. 

This makes for a simpler code btw, because we no longer have to worry about passing the theme everywhere. As long as we use 
```
import {styled} from 'baseui';
``` 

all the styled components have a $theme prop which is pre-populated with the BaseUI theme. 
This works fine on the development side. 

however with build, I get: 

```
 10 | function driver(style, styletron) {
  11 |   const tx = renderDeclarativeRules(style, styletron);
> 12 |   return styletron.renderStyle(tx);
     | ^
  13 | }
  14 | function getInitialStyle() {
  15 |   return {};


  WebpackError: TypeError: Cannot read property 'renderStyle' of undefined

  - index.es.js:12 driver
    [gatsby]/[styletron-standard]/dist/index.es.js:12:1

  - index.es.js:278 Object.StyledElement.Object [as children]
    [gatsby]/[styletron-react]/dist/index.es.js:278:1


  - bootstrap:24 a.read
    lib/webpack/bootstrap:24:1

  - bootstrap:36 renderToString
    lib/webpack/bootstrap:36:1
```

**Comment by jckr** [comment]
A possibility would be to just revert the work in #98 / #110 and use static, non-overridable values in the styled components, just to get the build going.

**Comment by ibgreen** [comment]
I seem to recall there being gatsby plugins to make libraries like styled, lodash etc available to gatsby, maybe we just need to do the same with styletron.

**Comment by jckr** [comment]
There's a gastby-plugin-styletron https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-styletron which does the same thing as the instructions for using styletron w/ gatsby. https://baseweb.design/getting-started/installation/ But I have the same errors when using it.

**Comment by jckr** [comment]
I feel the way forward is: 
- just remove all style customization via props / theme in styled components, so we can at least build the sites
- build sites
- reevaluate. My preferred long term solution is using base ui but if we can't get this to work easily - whatever works, including all CSS solution.

**Comment by ibgreen** [comment]
@jckr Seems to be two issues here (styling and overriding components) maybe split into two issues?
