### ISSUE TITLE
Integrate gatsby-remark-embedded-codesandbox

### ISSUE THREAD

**Issue by ibgreen** [uber-web/ocular#165]
Port the implementation in https://github.com/uber/nebula.gl/pull/217 into ocular.

@javidhsueh @jckr @georgios-uber

**Comment by georgios-uber** [comment]
Make sure it can be configured through ocular config.

**Comment by ibgreen** [comment]
> Make sure it can be configured through ocular config.

Are you talking about passing in options to https://github.com/uber/nebula.gl/blob/de49bed91af7ce66cff720c7843cda6dfa05e89c/website/gatsby-config.js#L14

**Comment by mletic** [comment]
This is fixed with #331 
Right now it's just included in the project, additional PR might be good to be able to configure the CodeSandbox plugin options from the Gatsby app that is using gatsby-theme-ocular.
