### ISSUE TITLE
Tracker: Better Error Messages

### ISSUE THREAD

**Issue by ibgreen** [uber-web/ocular#181]
Let's collect ideas for how to make ocular-gatsby easier to use by improving error messages.

- [x] Verify `ocular-config.js`: Add an object with default values for all supported keys and emit warnings if ocular-config contains any unknown keys. That could save users a lot of time.
- [x] `site-query.jsx` - If you upgrade ocular, and site-query has changed, you are in for a long painful debugging session... On startup, check that contents of `src/components/site-query.jsx` is the same as `node_modules/opcular-gatsby/...`.

**Comment by javidhsueh** [comment]
We're able to validate the ocular-config in #183 
Now it will print warning/error messages for unknown keys, invalid data type/shape, and the keys will be deprecated soon.
