### ISSUE TITLE
Ocular sites don't work in Edge/IE11

### ISSUE THREAD

**Issue by tsherif** [uber-web/ocular#254]
On Edge, there are several problems with how pages are rendering. I've listed the issues with the luma.gl website here: https://github.com/uber/luma.gl/issues/1239#issuecomment-534114306

Ocular-based sites don't load at all in IE11. This includes math.gl, loaders.gl and the in-development luma.gl site. I've noted where I believe the issue is for the luma.gl site here: https://github.com/uber/luma.gl/issues/1239#issuecomment-534117850

**Comment by ibgreen** [comment]
Fixing these is probably not hard, finding a windows machine to test on is the main problem...

**Comment by isaacbrodsky** [comment]
Microsoft makes VMs available to test with: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by tsherif** [comment]
Fixed by #256
