### ISSUE TITLE
Undefined variable: "$gradient-2"

### ISSUE THREAD

**Issue by javidhsueh** [uber-web/ocular#52]
I got this error in ocular@0.5.5 when starting the local server

> ERROR in ../css-loader??ref--5-1!../sass-loader/lib/loader.js??ref--5-2!../autoprefixer-loader!./base/styles/main.scss
Module build failed:
      border-image: $gradient-2;
                   ^
      Undefined variable: "$gradient-2".
      in /Users/javidhsueh/graph.gl/docs/node_modules/ocular/base/styles/_toc.scss (line 75, column 21)
 @ ./base/styles/main.scss 4:14-160 18:2-22:4 19:20-166
 @ ./base/components/App.js
 @ ./base/main.js
 @ multi ../webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch babel-polyfill whatwg-fetch ./base/main

**Comment by ibgreen** [comment]
Related to old ocular, closing
